<!--DRUPAL-->
<!--[if lte IE 8]>
<script src="common/js/html5shiv/html5shiv.min.js?v=3.7.3"></script>
<![endif]-->
<script src="common/js/jquery/jquery.min.js"></script>
<script src="common/js/jquery-once/jquery.once.min.js"></script>
<!--DRUPAL-->

<!--[if (lt IE 9) & (!IEMobile)]>
<script type="text/javascript" src="theme/js/lib/html5.js"></script>
<![endif]-->
<script type="text/javascript" src="theme/js/lib/device.min.js"></script>
<script type="text/javascript" src="theme/js/lib/jquery.browser.js"></script>
<script type="text/javascript" src="theme/js/lib/scrollreveal.min.js"></script>
<script type="text/javascript" src="theme/js/lib/slick.min.js"></script>
<!--<script type="text/javascript" src="theme/js/lib/bootstrap-modal.min.js"></script>-->
<script type="text/javascript" src="theme/js/js.js"></script>