<footer id="site-footer" class="site-footer">
  <div class="container">
    <div class="inner-wrap">
      <div class="contact">
        <p>
          530 B. Street, Suite 2300<br>
          San Diego, CA 92101
        </p>
        <div class="social">

          <div class="field field--name-field-facebook field--type-link field--label-hidden field__item"><a href="https://www.facebook.com/profile.php?id=100008262096727" class="ico ss-icon ss-social-regular  ss-facebook"></a></div>

          <div class="field field--name-field-twitter field--type-link field--label-hidden field__item"><a href="https://www.twitter.com" class="ico ss-icon ss-social-regular  ss-twitter"></a></div>

          <div class="field field--name-field-linkedin field--type-link field--label-hidden field__item"><a href="https://www.linkedin.com/company-beta/3326048/" class="ico ss-icon ss-social-regular  ss-linkedin"></a></div>

        </div>
      </div>
      <div class="logo">
        <a href="#"><img src="theme/images/logo-a.png" alt=""></a>
      </div>
    </div>
  </div>

  <svg class="clip-path" width="0" height="0">
    <defs>
      <clipPath id="type-top-right" clipPathUnits="objectBoundingBox">
        <polygon points="0 0,0.575 1,1 1,1 0"></polygon>
        <!--        <polygon points="0 0,546 619,948 619,948 0"></polygon>-->
      </clipPath>
      <clipPath id="type-middle-triangle" clipPathUnits="objectBoundingBox">
        <polygon points="0 0,1 0, 0.5 1"></polygon>
        <!--        <polygon points="0 0,950 0, 475 543"></polygon>-->
      </clipPath>
      <clipPath id="type-middle-triangle-mobile" clipPathUnits="objectBoundingBox">
        <polygon points="0 0,1 0, 1 0.66, 0.75 1"></polygon>
      </clipPath>
      <clipPath id="type-left" clipPathUnits="objectBoundingBox">
        <polygon points="0 0,1 0.636, 0.423 1,0 1"></polygon>
        <!--        <polygon points="0 0,826 942, 350 1481,0 1481"></polygon>-->
      </clipPath>
      <clipPath id="type-left-mobile" clipPathUnits="objectBoundingBox">
        <polygon points="0 0, 0 1, 1 0.5"></polygon>
      </clipPath>
      <clipPath id="type-bottom-right"  clipPathUnits="objectBoundingBox">
        <polygon points="1 0,1 1, 0 1"></polygon>
      </clipPath>
      <clipPath id="type-bottom-right-mobile"  clipPathUnits="objectBoundingBox">
        <polygon points="1 0,1 1, 0 1, 0 0.8"></polygon>
      </clipPath>
      <clipPath id="title-page" clipPathUnits="objectBoundingBox">
        <polygon points="0 0,0.195 1, 1 1, 1 0"></polygon>
        <!--        <polygon points="0 0,185 210, 948 210, 948 0"></polygon>-->
      </clipPath>
      <clipPath id="title-page-mobile" clipPathUnits="objectBoundingBox">
        <polygon points="0 0,0.609 1, 1 1, 1 0"></polygon>
      </clipPath>
      <clipPath id="b-with-photo" clipPathUnits="objectBoundingBox">
        <polygon points="0 0,0.621 1,1 1, 1 0"></polygon>
        <!--        <polygon points="0 0,465 529,748 529, 748 0"></polygon>-->
      </clipPath>
      <clipPath id="b-with-photo-a" clipPathUnits="objectBoundingBox">
        <polygon points="0 0, 0 0.12, 0.665 0.946,1 0.946, 1 0"></polygon>
      </clipPath>
      <clipPath id="b-with-photo-b" clipPathUnits="objectBoundingBox">
        <polygon points="0 0,0.35 1,1 1, 1 0"></polygon>
      </clipPath>
      <clipPath id="b-with-photo-c" clipPathUnits="objectBoundingBox">
        <polygon points="0 0,0.741 1,1 1, 1 0"></polygon>
      </clipPath>
      <clipPath id="b-with-photo-mobile" clipPathUnits="objectBoundingBox">
        <polygon points="0 0,0 1,1 1, 0.728 0"></polygon>
      </clipPath>
      <clipPath id="clip-site-footer" clipPathUnits="objectBoundingBox">
        <polygon points="0 0,1 0,0 1"></polygon>
      </clipPath>

      <clipPath id="left-bg">
        <polygon points="0 0,0 650,1010 650, 454 0"></polygon>
      </clipPath>
      <clipPath id="right-bg">
        <polygon points="0 0,557 650,847 650,847 0"></polygon>
      </clipPath>
      <clipPath id="section-top-left-bg">
        <polygon points="0 0,0 646,290 646,844 0"></polygon>
      </clipPath>
      <clipPath id="section-top-right-bg">
        <polygon points="554 0,1010 0,1010 646,0 646"></polygon>
      </clipPath>
    </defs>
  </svg>
</footer>