<header id="site-header" class="site-header">
  <div class="container">
    <div class="logo">
      <a href="index.php"><img src="theme/images/logo-new.png" alt=""></a>
    </div>
    <nav class="nav">
      <a href="#" class="btn-nav mobile-only">
      </a>
      <ul class="menu">
        <li><a href="#">WHAT WE DO</a></li>
        <li class="active"><a href="#">WHO WE ARE</a>
          <!--          <ul>-->
          <!--            <li class="active"><a href="#">STAFF</a></li>-->
          <!--            <li><a href="#">MISSION</a></li>-->
          <!--          </ul>-->
        </li>
        <li><a href="#">ENDORSEMENTS</a></li>
        <li><a href="#">CONTACT</a></li>
        <li><a href="#">CAREERS</a></li>
      </ul>
    </nav>
  </div>
  <div class="bg">
    <span></span>
  </div>
</header>